from PyQt6 import QtCore, QtWidgets


class Ui_Main_AddGain(object):
    def setupUi(self, Main_AddGain):
        Main_AddGain.setObjectName("Main_AddGain")
        Main_AddGain.resize(240, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Main_AddGain)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 191, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Main_AddGain)
        self.buttonBox.setGeometry(QtCore.QRect(20, 270, 191, 20))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Main_AddGain)
        QtCore.QMetaObject.connectSlotsByName(Main_AddGain)

    def retranslateUi(self, Main_AddGain):
        _translate = QtCore.QCoreApplication.translate
        Main_AddGain.setWindowTitle(_translate("Main_AddGain", "Добавить в Доходы"))
        self.label_3.setText(_translate("Main_AddGain", "Сумма"))
        self.label_4.setText(_translate("Main_AddGain", "Примечание"))
        self.label_2.setText(_translate("Main_AddGain", "Имя"))
        self.comboBox.setItemText(0, _translate("Main_AddGain", "Зарплата"))
        self.comboBox.setItemText(1, _translate("Main_AddGain", "Инвестиции"))
        self.comboBox.setItemText(2, _translate("Main_AddGain", "Подарки"))
        self.comboBox.setItemText(3, _translate("Main_AddGain", "Недвижимость"))
        self.lineEdit_2.setPlaceholderText(_translate("Main_AddGain", "₽"))
        self.label.setText(_translate("Main_AddGain", "Категория"))