from PyQt6 import QtCore, QtWidgets


class Ui_Main_AddExpense(object):
    def setupUi(self, Main_AddExpense):
        Main_AddExpense.setObjectName("Main_AddExpense")
        Main_AddExpense.resize(240, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Main_AddExpense)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 203, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Main_AddExpense)
        self.buttonBox.setGeometry(QtCore.QRect(20, 270, 201, 20))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Main_AddExpense)
        QtCore.QMetaObject.connectSlotsByName(Main_AddExpense)

    def retranslateUi(self, Main_AddExpense):
        _translate = QtCore.QCoreApplication.translate
        Main_AddExpense.setWindowTitle(_translate("Main_AddExpense", "Добавить в Расходы"))
        self.label.setText(_translate("Main_AddExpense", "Категория"))
        self.lineEdit_2.setPlaceholderText(_translate("Main_AddExpense", "₽"))
        self.comboBox.setItemText(0, _translate("Main_AddExpense", "Рестораны"))
        self.comboBox.setItemText(1, _translate("Main_AddExpense", "Образование"))
        self.comboBox.setItemText(2, _translate("Main_AddExpense", "Кафе"))
        self.comboBox.setItemText(3, _translate("Main_AddExpense", "Транспорт"))
        self.comboBox.setItemText(4, _translate("Main_AddExpense", "Одежда"))
        self.comboBox.setItemText(5, _translate("Main_AddExpense", "Продукты"))
        self.comboBox.setItemText(6, _translate("Main_AddExpense", "Развлечения"))
        self.comboBox.setItemText(7, _translate("Main_AddExpense", "Путешествия"))
        self.comboBox.setItemText(8, _translate("Main_AddExpense", "Здоровье"))
        self.label_2.setText(_translate("Main_AddExpense", "Имя"))
        self.label_3.setText(_translate("Main_AddExpense", "Сумма"))
        self.label_4.setText(_translate("Main_AddExpense", "Примечание"))