from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reg_AddIncome(object):
    def setupUi(self, Reg_AddIncome):
        Reg_AddIncome.setObjectName("Reg_AddIncome")
        Reg_AddIncome.resize(240, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Reg_AddIncome)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 201, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.day_radbtn = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_radbtn.sizePolicy().hasHeightForWidth())
        self.day_radbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.day_radbtn.setFont(font)
        self.day_radbtn.setObjectName("day_radbtn")
        self.buttonGroup = QtWidgets.QButtonGroup(Reg_AddIncome)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.day_radbtn)
        self.verticalLayout_2.addWidget(self.day_radbtn)
        self.moth_radbtn = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moth_radbtn.sizePolicy().hasHeightForWidth())
        self.moth_radbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.moth_radbtn.setFont(font)
        self.moth_radbtn.setObjectName("moth_radbtn")
        self.buttonGroup.addButton(self.moth_radbtn)
        self.verticalLayout_2.addWidget(self.moth_radbtn)
        self.year_radbtn = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_radbtn.sizePolicy().hasHeightForWidth())
        self.year_radbtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.year_radbtn.setFont(font)
        self.year_radbtn.setObjectName("year_radbtn")
        self.buttonGroup.addButton(self.year_radbtn)
        self.verticalLayout_2.addWidget(self.year_radbtn)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Reg_AddIncome)
        self.buttonBox.setGeometry(QtCore.QRect(30, 270, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Reg_AddIncome)
        QtCore.QMetaObject.connectSlotsByName(Reg_AddIncome)

    def retranslateUi(self, Reg_AddIncome):
        _translate = QtCore.QCoreApplication.translate
        Reg_AddIncome.setWindowTitle(_translate("Reg_AddIncome", "Добавить в Заработки"))
        self.label.setText(_translate("Reg_AddIncome", "Категория"))
        self.label_3.setText(_translate("Reg_AddIncome", "Сумма"))
        self.lineEdit_2.setPlaceholderText(_translate("Reg_AddIncome", "₽"))
        self.label_2.setText(_translate("Reg_AddIncome", "Имя"))
        self.comboBox.setItemText(0, _translate("Reg_AddIncome", "Зарплата"))
        self.comboBox.setItemText(1, _translate("Reg_AddIncome", "Инвестиции"))
        self.comboBox.setItemText(2, _translate("Reg_AddIncome", "Недвижимость"))
        self.day_radbtn.setText(_translate("Reg_AddIncome", "День"))
        self.moth_radbtn.setText(_translate("Reg_AddIncome", "Месяц"))
        self.year_radbtn.setText(_translate("Reg_AddIncome", "Год"))
        self.label_4.setText(_translate("Reg_AddIncome", "Период"))
